@ECHO OFF
mkdir Apps
cd "C:\Users\runneradmin\Desktop\Apps"
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/7z2107-x64_silent.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/BraveBrowserSetup.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/FileZilla.v3.45.1.64-bit._silent.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/raw/main/allinone/root/IDM-6.41.3-AIO-Silent-Install.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/MEGAsyncSetup64_silent.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/MyLanViewer-setup_silent.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/MySFXInstaller.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/npp.8.3.3.Installer.x64_silent.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/NTH.-.1.Click.DirectX.9.0.June.2010.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/NTH.-.1.Click.Foxit.10.0.0.35798.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/NTH.-.1.Click.Klite.15.5.0.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/NTH.-.1.Click.TeamViewer.15.6.7.0.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/NTH.-.1.Click.UltraISO.Premium.9.7.2.3561.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/NTH.-.1.Click.Unlocker.1.9.2.Final.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/raw/main/allinone/root/Java-SE-8u221-x32-x64.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/OneDriveSetup_silent.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/peazip-8.3.0.WIN64_silent.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/PowerISO.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/qbittorrent_4.4.2_x64_setup_silent.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/vlc-3.0.16-win64_silent.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/releases/download/Apps/WinRAR.6.02.en.Silent.Install.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/raw/main/allinone/root/IntelliJ_IDEA_SILEN.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/raw/main/allinone/root/ideaIC-2022.2.3.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/raw/main/allinone/root/android-studio-.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/raw/main/allinone/root/android-studio-_silent.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/raw/main/allinone/root/Sib.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/raw/main/allinone/root/StudioPortable.7z
aria2c.exe https://github.com/brincon2/ANY-VPS/raw/main/allinone/root/ThinAppPortable.exe
aria2c.exe https://raw.githubusercontent.com/brincon2/ANY-VPS/main/allinone/install-basic-software.cmd
aria2c.exe https://github.com/brincon2/ANY-VPS/raw/main/allinone/root/Silent-Install-Builder-v6.1.1.exe
aria2c.exe https://github.com/brincon2/ANY-VPS/raw/main/allinone/root/AppNee.com.VMware.ThinApp.Enterprise.v2206.0.0.Portable.FR.7z
